<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Create admin user if it doesn't exist
        User::firstOrCreate(
            ['email' => 'admin@example.com'],
            [
                'name' => 'Admin',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
            ]
        );

        // Create categories if they don't exist
        $categories = [
            ['name' => 'Bowls', 'slug' => 'bowls'],
            ['name' => 'Cups', 'slug' => 'cups'],
            ['name' => 'Spoons', 'slug' => 'spoons'],
            ['name' => 'Plates', 'slug' => 'plates'],
            ['name' => 'Lunch Bowls', 'slug' => 'lunch-bowls'],
            ['name' => 'Bottles', 'slug' => 'bottles'],
            ['name' => 'Gift Bags', 'slug' => 'gift-bags'],
        ];

        foreach ($categories as $categoryData) {
            Category::firstOrCreate(
                ['slug' => $categoryData['slug']],
                $categoryData
            );
        }

        // Get all categories
        $bowlCategory = Category::where('slug', 'bowls')->first();
        $cupCategory = Category::where('slug', 'cups')->first();
        $spoonCategory = Category::where('slug', 'spoons')->first();
        $plateCategory = Category::where('slug', 'plates')->first();
        $lunchBowlCategory = Category::where('slug', 'lunch-bowls')->first();
        $bottleCategory = Category::where('slug', 'bottles')->first();
        $giftBagCategory = Category::where('slug', 'gift-bags')->first();

        // Create 10 products for Bowls category
        if ($bowlCategory) {
            $bowlProducts = [
                [
                    'name' => 'Transparent Plastic Bowl - Small',
                    'slug' => 'transparent-plastic-bowl-small',
                    'description' => 'High-quality transparent plastic bowl, perfect for parties and events.',
                    'price' => 2.50,
                    'quantity' => 100,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'bowl',
                    'size' => 'small',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Bowl - Medium',
                    'slug' => 'transparent-plastic-bowl-medium',
                    'description' => 'Medium-sized transparent plastic bowl, ideal for serving.',
                    'price' => 3.50,
                    'quantity' => 100,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'bowl',
                    'size' => 'medium',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Bowl - Large',
                    'slug' => 'transparent-plastic-bowl-large',
                    'description' => 'Large transparent plastic bowl for big servings and gatherings.',
                    'price' => 4.50,
                    'quantity' => 80,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bowl',
                    'size' => 'large',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'White Plastic Bowl - Small',
                    'slug' => 'white-plastic-bowl-small',
                    'description' => 'Elegant white plastic bowl, perfect for everyday use.',
                    'price' => 2.00,
                    'quantity' => 120,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bowl',
                    'size' => 'small',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Bowl - Medium',
                    'slug' => 'white-plastic-bowl-medium',
                    'description' => 'Stylish medium white plastic bowl for serving dishes.',
                    'price' => 3.00,
                    'quantity' => 110,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bowl',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Bowl - Large',
                    'slug' => 'white-plastic-bowl-large',
                    'description' => 'Large white plastic bowl ideal for family meals.',
                    'price' => 4.00,
                    'quantity' => 90,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bowl',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'Colorful Plastic Bowl Set - Small',
                    'slug' => 'colorful-plastic-bowl-small',
                    'description' => 'Vibrant small plastic bowls available in assorted colors.',
                    'price' => 2.25,
                    'quantity' => 150,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'bowl',
                    'size' => 'small',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Colorful Plastic Bowl Set - Medium',
                    'slug' => 'colorful-plastic-bowl-medium',
                    'description' => 'Bright medium plastic bowls in various colors for parties.',
                    'price' => 3.25,
                    'quantity' => 140,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bowl',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Premium Plastic Bowl - Medium',
                    'slug' => 'premium-plastic-bowl-medium',
                    'description' => 'High-quality premium plastic bowl with enhanced durability.',
                    'price' => 3.75,
                    'quantity' => 95,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'bowl',
                    'size' => 'medium',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Premium Plastic Bowl - Large',
                    'slug' => 'premium-plastic-bowl-large',
                    'description' => 'Durable large premium plastic bowl for commercial use.',
                    'price' => 5.00,
                    'quantity' => 75,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bowl',
                    'size' => 'large',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
            ];

            foreach ($bowlProducts as $product) {
                $product['category_id'] = $bowlCategory->id;
                Product::updateOrCreate(
                    ['slug' => $product['slug']],
                    $product
                );
            }
        }

        // Create 10 products for Cups category
        if ($cupCategory) {
            $cupProducts = [
                [
                    'name' => 'Transparent Plastic Cup - Small',
                    'slug' => 'transparent-plastic-cup-small',
                    'description' => 'Clear small plastic cups perfect for shots and small servings.',
                    'price' => 1.00,
                    'quantity' => 200,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'cup',
                    'size' => 'small',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Cup - Medium',
                    'slug' => 'transparent-plastic-cup-medium',
                    'description' => 'Clear plastic cups for beverages, ideal for parties.',
                    'price' => 1.50,
                    'quantity' => 200,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'cup',
                    'size' => 'medium',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Cup - Large',
                    'slug' => 'transparent-plastic-cup-large',
                    'description' => 'Large clear plastic cups for big drinks and smoothies.',
                    'price' => 2.00,
                    'quantity' => 180,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'cup',
                    'size' => 'large',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'White Plastic Cup - Small',
                    'slug' => 'white-plastic-cup-small',
                    'description' => 'Elegant small white plastic cups for coffee and tea.',
                    'price' => 1.25,
                    'quantity' => 190,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'cup',
                    'size' => 'small',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Cup - Medium',
                    'slug' => 'white-plastic-cup-medium',
                    'description' => 'Classic medium white plastic cups for everyday use.',
                    'price' => 1.75,
                    'quantity' => 200,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'cup',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Cup - Large',
                    'slug' => 'white-plastic-cup-large',
                    'description' => 'Large white plastic cups perfect for cold beverages.',
                    'price' => 2.25,
                    'quantity' => 170,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'cup',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'Colorful Plastic Cup Set - Medium',
                    'slug' => 'colorful-plastic-cup-medium',
                    'description' => 'Vibrant medium plastic cups in assorted colors for parties.',
                    'price' => 1.60,
                    'quantity' => 220,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'cup',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Colorful Plastic Cup Set - Large',
                    'slug' => 'colorful-plastic-cup-large',
                    'description' => 'Bright large plastic cups in various colors for events.',
                    'price' => 2.10,
                    'quantity' => 200,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'cup',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Premium Plastic Cup - Medium',
                    'slug' => 'premium-plastic-cup-medium',
                    'description' => 'High-quality premium plastic cup with enhanced durability.',
                    'price' => 2.00,
                    'quantity' => 150,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'cup',
                    'size' => 'medium',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Premium Plastic Cup - Large',
                    'slug' => 'premium-plastic-cup-large',
                    'description' => 'Durable large premium plastic cup for commercial use.',
                    'price' => 2.50,
                    'quantity' => 140,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'cup',
                    'size' => 'large',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
            ];

            foreach ($cupProducts as $product) {
                $product['category_id'] = $cupCategory->id;
                Product::updateOrCreate(
                    ['slug' => $product['slug']],
                    $product
                );
            }
        }

        // Create 10 products for Spoons category
        if ($spoonCategory) {
            $spoonProducts = [
                [
                    'name' => 'Transparent Plastic Spoon - Small',
                    'slug' => 'transparent-plastic-spoon-small',
                    'description' => 'Clear small plastic spoons perfect for desserts and samples.',
                    'price' => 0.50,
                    'quantity' => 500,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'spoon',
                    'size' => 'small',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Spoon - Medium',
                    'slug' => 'transparent-plastic-spoon-medium',
                    'description' => 'Clear medium plastic spoons ideal for general use.',
                    'price' => 0.75,
                    'quantity' => 500,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'spoon',
                    'size' => 'medium',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Spoon - Large',
                    'slug' => 'transparent-plastic-spoon-large',
                    'description' => 'Large clear plastic spoons for soups and main dishes.',
                    'price' => 1.00,
                    'quantity' => 400,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'spoon',
                    'size' => 'large',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'White Plastic Spoon - Small',
                    'slug' => 'white-plastic-spoon-small',
                    'description' => 'Elegant small white plastic spoons for coffee and tea.',
                    'price' => 0.60,
                    'quantity' => 480,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'spoon',
                    'size' => 'small',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Spoon - Medium',
                    'slug' => 'white-plastic-spoon-medium',
                    'description' => 'Classic medium white plastic spoons for everyday use.',
                    'price' => 0.85,
                    'quantity' => 500,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'spoon',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Spoon - Large',
                    'slug' => 'white-plastic-spoon-large',
                    'description' => 'Large white plastic spoons perfect for serving.',
                    'price' => 1.10,
                    'quantity' => 450,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'spoon',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'Colorful Plastic Spoon Set - Medium',
                    'slug' => 'colorful-plastic-spoon-medium',
                    'description' => 'Vibrant medium plastic spoons in assorted colors for parties.',
                    'price' => 0.80,
                    'quantity' => 520,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'spoon',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Colorful Plastic Spoon Set - Large',
                    'slug' => 'colorful-plastic-spoon-large',
                    'description' => 'Bright large plastic spoons in various colors for events.',
                    'price' => 1.05,
                    'quantity' => 480,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'spoon',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Premium Plastic Spoon - Medium',
                    'slug' => 'premium-plastic-spoon-medium',
                    'description' => 'High-quality premium plastic spoon with enhanced durability.',
                    'price' => 1.00,
                    'quantity' => 350,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'spoon',
                    'size' => 'medium',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Premium Plastic Spoon - Large',
                    'slug' => 'premium-plastic-spoon-large',
                    'description' => 'Durable large premium plastic spoon for commercial use.',
                    'price' => 1.25,
                    'quantity' => 320,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'spoon',
                    'size' => 'large',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
            ];

            foreach ($spoonProducts as $product) {
                $product['category_id'] = $spoonCategory->id;
                Product::updateOrCreate(
                    ['slug' => $product['slug']],
                    $product
                );
            }
        }

        // Create 10 products for Plates category
        if ($plateCategory) {
            $plateProducts = [
                [
                    'name' => 'Transparent Plastic Plate - Small',
                    'slug' => 'transparent-plastic-plate-small',
                    'description' => 'Clear small plastic plates perfect for appetizers and snacks.',
                    'price' => 1.50,
                    'quantity' => 300,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'plate',
                    'size' => 'small',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Plate - Medium',
                    'slug' => 'transparent-plastic-plate-medium',
                    'description' => 'Clear medium plastic plates ideal for main courses.',
                    'price' => 2.50,
                    'quantity' => 300,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'plate',
                    'size' => 'medium',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Plate - Large',
                    'slug' => 'transparent-plastic-plate-large',
                    'description' => 'Large clear plastic plates for big meals and buffets.',
                    'price' => 3.50,
                    'quantity' => 250,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'plate',
                    'size' => 'large',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'White Plastic Plate - Small',
                    'slug' => 'white-plastic-plate-small',
                    'description' => 'Elegant small white plastic plates for appetizers.',
                    'price' => 1.75,
                    'quantity' => 280,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'plate',
                    'size' => 'small',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Plate - Medium',
                    'slug' => 'white-plastic-plate-medium',
                    'description' => 'Classic medium white plastic plates for everyday meals.',
                    'price' => 2.75,
                    'quantity' => 300,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'plate',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Plate - Large',
                    'slug' => 'white-plastic-plate-large',
                    'description' => 'Large white plastic plates perfect for family dinners.',
                    'price' => 3.75,
                    'quantity' => 270,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'plate',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'Colorful Plastic Plate Set - Medium',
                    'slug' => 'colorful-plastic-plate-medium',
                    'description' => 'Vibrant medium plastic plates in assorted colors for parties.',
                    'price' => 2.60,
                    'quantity' => 320,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'plate',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Colorful Plastic Plate Set - Large',
                    'slug' => 'colorful-plastic-plate-large',
                    'description' => 'Bright large plastic plates in various colors for events.',
                    'price' => 3.60,
                    'quantity' => 290,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'plate',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Premium Plastic Plate - Medium',
                    'slug' => 'premium-plastic-plate-medium',
                    'description' => 'High-quality premium plastic plate with enhanced durability.',
                    'price' => 3.00,
                    'quantity' => 200,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'plate',
                    'size' => 'medium',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Premium Plastic Plate - Large',
                    'slug' => 'premium-plastic-plate-large',
                    'description' => 'Durable large premium plastic plate for commercial use.',
                    'price' => 4.00,
                    'quantity' => 180,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'plate',
                    'size' => 'large',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
            ];

            foreach ($plateProducts as $product) {
                $product['category_id'] = $plateCategory->id;
                Product::updateOrCreate(
                    ['slug' => $product['slug']],
                    $product
                );
            }
        }

        // Create 10 products for Lunch Bowls category
        if ($lunchBowlCategory) {
            $lunchBowlProducts = [
                [
                    'name' => 'Transparent Plastic Lunch Bowl - Small',
                    'slug' => 'transparent-plastic-lunch-bowl-small',
                    'description' => 'Clear small lunch bowl perfect for light meals and salads.',
                    'price' => 3.00,
                    'quantity' => 150,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'lunch_bowl',
                    'size' => 'small',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Lunch Bowl - Medium',
                    'slug' => 'transparent-plastic-lunch-bowl-medium',
                    'description' => 'Clear medium lunch bowl ideal for regular meals.',
                    'price' => 4.00,
                    'quantity' => 150,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'lunch_bowl',
                    'size' => 'medium',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Transparent Plastic Lunch Bowl - Large',
                    'slug' => 'transparent-plastic-lunch-bowl-large',
                    'description' => 'Large clear lunch bowl for hearty meals and large portions.',
                    'price' => 5.00,
                    'quantity' => 120,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'lunch_bowl',
                    'size' => 'large',
                    'material' => 'Transparent Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'White Plastic Lunch Bowl - Small',
                    'slug' => 'white-plastic-lunch-bowl-small',
                    'description' => 'Elegant small white lunch bowl for salads and light meals.',
                    'price' => 3.25,
                    'quantity' => 140,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'lunch_bowl',
                    'size' => 'small',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Lunch Bowl - Medium',
                    'slug' => 'white-plastic-lunch-bowl-medium',
                    'description' => 'Classic medium white lunch bowl for everyday meals.',
                    'price' => 4.25,
                    'quantity' => 150,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'lunch_bowl',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'White Plastic Lunch Bowl - Large',
                    'slug' => 'white-plastic-lunch-bowl-large',
                    'description' => 'Large white lunch bowl perfect for substantial meals.',
                    'price' => 5.25,
                    'quantity' => 130,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'lunch_bowl',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'Colorful Plastic Lunch Bowl Set - Medium',
                    'slug' => 'colorful-plastic-lunch-bowl-medium',
                    'description' => 'Vibrant medium lunch bowls in assorted colors for parties.',
                    'price' => 4.10,
                    'quantity' => 160,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'lunch_bowl',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Colorful Plastic Lunch Bowl Set - Large',
                    'slug' => 'colorful-plastic-lunch-bowl-large',
                    'description' => 'Bright large lunch bowls in various colors for events.',
                    'price' => 5.10,
                    'quantity' => 140,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'lunch_bowl',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Premium Plastic Lunch Bowl - Medium',
                    'slug' => 'premium-plastic-lunch-bowl-medium',
                    'description' => 'High-quality premium lunch bowl with enhanced durability.',
                    'price' => 4.50,
                    'quantity' => 100,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'lunch_bowl',
                    'size' => 'medium',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Premium Plastic Lunch Bowl - Large',
                    'slug' => 'premium-plastic-lunch-bowl-large',
                    'description' => 'Durable large premium lunch bowl for commercial use.',
                    'price' => 5.50,
                    'quantity' => 90,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'lunch_bowl',
                    'size' => 'large',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
            ];

            foreach ($lunchBowlProducts as $product) {
                $product['category_id'] = $lunchBowlCategory->id;
                Product::updateOrCreate(
                    ['slug' => $product['slug']],
                    $product
                );
            }
        }

        // Create 10 products for Bottles category
        if ($bottleCategory) {
            $bottleProducts = [
                [
                    'name' => 'Plastic Water Bottle - 250ml',
                    'slug' => 'plastic-water-bottle-250ml',
                    'description' => 'Compact 250ml water bottle, perfect for small servings.',
                    'price' => 2.00,
                    'quantity' => 150,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'bottle',
                    'size' => 'small',
                    'capacity' => '250ml',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Plastic Water Bottle - 350ml',
                    'slug' => 'plastic-water-bottle-350ml',
                    'description' => '350ml water bottle, great for events.',
                    'price' => 2.50,
                    'quantity' => 150,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'bottle',
                    'size' => 'medium',
                    'capacity' => '350ml',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Plastic Water Bottle - 500ml',
                    'slug' => 'plastic-water-bottle-500ml',
                    'description' => 'Large 500ml water bottle for parties and restaurants.',
                    'price' => 3.00,
                    'quantity' => 150,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'bottle',
                    'size' => 'medium',
                    'capacity' => '500ml',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Plastic Water Bottle - 750ml',
                    'slug' => 'plastic-water-bottle-750ml',
                    'description' => 'Extra large 750ml water bottle for extended use.',
                    'price' => 3.50,
                    'quantity' => 130,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bottle',
                    'size' => 'large',
                    'capacity' => '750ml',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Plastic Water Bottle - 1L',
                    'slug' => 'plastic-water-bottle-1l',
                    'description' => 'Large 1 liter water bottle perfect for all-day hydration.',
                    'price' => 4.00,
                    'quantity' => 120,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bottle',
                    'size' => 'large',
                    'capacity' => '1L',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Colored Plastic Water Bottle - 500ml',
                    'slug' => 'colored-plastic-water-bottle-500ml',
                    'description' => 'Stylish 500ml water bottle available in various colors.',
                    'price' => 3.25,
                    'quantity' => 140,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bottle',
                    'size' => 'medium',
                    'capacity' => '500ml',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Premium Plastic Water Bottle - 500ml',
                    'slug' => 'premium-plastic-water-bottle-500ml',
                    'description' => 'High-quality premium 500ml water bottle with enhanced durability.',
                    'price' => 3.50,
                    'quantity' => 110,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'bottle',
                    'size' => 'medium',
                    'capacity' => '500ml',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Premium Plastic Water Bottle - 750ml',
                    'slug' => 'premium-plastic-water-bottle-750ml',
                    'description' => 'Durable premium 750ml water bottle for commercial use.',
                    'price' => 4.00,
                    'quantity' => 100,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bottle',
                    'size' => 'large',
                    'capacity' => '750ml',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Sports Plastic Water Bottle - 500ml',
                    'slug' => 'sports-plastic-water-bottle-500ml',
                    'description' => 'Ergonomic 500ml sports water bottle with easy-grip design.',
                    'price' => 3.75,
                    'quantity' => 125,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'bottle',
                    'size' => 'medium',
                    'capacity' => '500ml',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Sports Plastic Water Bottle - 750ml',
                    'slug' => 'sports-plastic-water-bottle-750ml',
                    'description' => 'Large 750ml sports water bottle perfect for active lifestyles.',
                    'price' => 4.25,
                    'quantity' => 115,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'bottle',
                    'size' => 'large',
                    'capacity' => '750ml',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
            ];

            foreach ($bottleProducts as $product) {
                $product['category_id'] = $bottleCategory->id;
                Product::updateOrCreate(
                    ['slug' => $product['slug']],
                    $product
                );
            }
        }

        // Create 10 products for Gift Bags category
        if ($giftBagCategory) {
            $giftBagProducts = [
                [
                    'name' => 'Small Gift Bag - Clear',
                    'slug' => 'small-gift-bag-clear',
                    'description' => 'Transparent small gift bag perfect for small presents.',
                    'price' => 1.00,
                    'quantity' => 200,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'gift_bag',
                    'size' => 'small',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Medium Gift Bag - Clear',
                    'slug' => 'medium-gift-bag-clear',
                    'description' => 'Clear medium gift bag ideal for regular-sized gifts.',
                    'price' => 1.50,
                    'quantity' => 200,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'gift_bag',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Large Gift Bag - Clear',
                    'slug' => 'large-gift-bag-clear',
                    'description' => 'Large clear gift bag for big presents and multiple items.',
                    'price' => 2.00,
                    'quantity' => 180,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'gift_bag',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Small Gift Bag - White',
                    'slug' => 'small-gift-bag-white',
                    'description' => 'Elegant small white gift bag for special occasions.',
                    'price' => 1.25,
                    'quantity' => 190,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'gift_bag',
                    'size' => 'small',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'Medium Gift Bag - White',
                    'slug' => 'medium-gift-bag-white',
                    'description' => 'Classic medium white gift bag for everyday gifting.',
                    'price' => 1.75,
                    'quantity' => 200,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'gift_bag',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'Large Gift Bag - White',
                    'slug' => 'large-gift-bag-white',
                    'description' => 'Large white gift bag perfect for multiple gifts.',
                    'price' => 2.25,
                    'quantity' => 170,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'gift_bag',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'White',
                ],
                [
                    'name' => 'Colorful Gift Bag Set - Medium',
                    'slug' => 'colorful-gift-bag-medium',
                    'description' => 'Vibrant medium gift bags in assorted colors for parties.',
                    'price' => 1.60,
                    'quantity' => 220,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'gift_bag',
                    'size' => 'medium',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Colorful Gift Bag Set - Large',
                    'slug' => 'colorful-gift-bag-large',
                    'description' => 'Bright large gift bags in various colors for events.',
                    'price' => 2.10,
                    'quantity' => 200,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'gift_bag',
                    'size' => 'large',
                    'material' => 'Plastic',
                    'color' => 'Assorted',
                ],
                [
                    'name' => 'Premium Gift Bag - Medium',
                    'slug' => 'premium-gift-bag-medium',
                    'description' => 'High-quality premium gift bag with enhanced durability.',
                    'price' => 2.00,
                    'quantity' => 150,
                    'is_active' => true,
                    'is_featured' => true,
                    'product_type' => 'gift_bag',
                    'size' => 'medium',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
                [
                    'name' => 'Premium Gift Bag - Large',
                    'slug' => 'premium-gift-bag-large',
                    'description' => 'Durable large premium gift bag for commercial use.',
                    'price' => 2.50,
                    'quantity' => 140,
                    'is_active' => true,
                    'is_featured' => false,
                    'product_type' => 'gift_bag',
                    'size' => 'large',
                    'material' => 'Premium Plastic',
                    'color' => 'Clear',
                ],
            ];

            foreach ($giftBagProducts as $product) {
                $product['category_id'] = $giftBagCategory->id;
                Product::updateOrCreate(
                    ['slug' => $product['slug']],
                    $product
                );
            }
        }
    }
}

